// Code generated by protoc-gen-go. DO NOT EDIT.
// source: location.proto

package location

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LatLng struct {
	Lat                  float32  `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float32  `protobuf:"fixed32,2,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatLng) Reset()         { *m = LatLng{} }
func (m *LatLng) String() string { return proto.CompactTextString(m) }
func (*LatLng) ProtoMessage()    {}
func (*LatLng) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{0}
}

func (m *LatLng) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatLng.Unmarshal(m, b)
}
func (m *LatLng) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatLng.Marshal(b, m, deterministic)
}
func (m *LatLng) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatLng.Merge(m, src)
}
func (m *LatLng) XXX_Size() int {
	return xxx_messageInfo_LatLng.Size(m)
}
func (m *LatLng) XXX_DiscardUnknown() {
	xxx_messageInfo_LatLng.DiscardUnknown(m)
}

var xxx_messageInfo_LatLng proto.InternalMessageInfo

func (m *LatLng) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *LatLng) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type StringResp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringResp) Reset()         { *m = StringResp{} }
func (m *StringResp) String() string { return proto.CompactTextString(m) }
func (*StringResp) ProtoMessage()    {}
func (*StringResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{1}
}

func (m *StringResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringResp.Unmarshal(m, b)
}
func (m *StringResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringResp.Marshal(b, m, deterministic)
}
func (m *StringResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringResp.Merge(m, src)
}
func (m *StringResp) XXX_Size() int {
	return xxx_messageInfo_StringResp.Size(m)
}
func (m *StringResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StringResp.DiscardUnknown(m)
}

var xxx_messageInfo_StringResp proto.InternalMessageInfo

func (m *StringResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*LatLng)(nil), "LatLng")
	proto.RegisterType((*StringResp)(nil), "StringResp")
}

func init() { proto.RegisterFile("location.proto", fileDescriptor_4f0f35158dcf9f2c) }

var fileDescriptor_4f0f35158dcf9f2c = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xc9, 0x4f, 0x4e,
	0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe1, 0x62, 0xf3, 0x49,
	0x2c, 0xf1, 0xc9, 0x4b, 0x17, 0x12, 0xe0, 0x62, 0xce, 0x49, 0x2c, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0x60, 0x0a, 0x02, 0x31, 0xc1, 0x22, 0x79, 0xe9, 0x12, 0x4c, 0x50, 0x91, 0xbc, 0x74, 0x25, 0x35,
	0x2e, 0xae, 0xe0, 0x92, 0xa2, 0xcc, 0xbc, 0xf4, 0xa0, 0xd4, 0xe2, 0x02, 0x21, 0x09, 0x2e, 0xf6,
	0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0xb0, 0x2e, 0xce, 0x20, 0x18, 0xd7, 0x48, 0x9b, 0x8b,
	0xc3, 0x07, 0x6a, 0x8f, 0x90, 0x3c, 0x17, 0x6b, 0x40, 0x51, 0x66, 0x5e, 0x89, 0x10, 0xbb, 0x1e,
	0xc4, 0x26, 0x29, 0x6e, 0x3d, 0x84, 0x21, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x97, 0x18, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x30, 0x14, 0xd6, 0x9c, 0x9b, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LocationClient is the client API for Location service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LocationClient interface {
	Print(ctx context.Context, in *LatLng, opts ...grpc.CallOption) (*StringResp, error)
}

type locationClient struct {
	cc *grpc.ClientConn
}

func NewLocationClient(cc *grpc.ClientConn) LocationClient {
	return &locationClient{cc}
}

func (c *locationClient) Print(ctx context.Context, in *LatLng, opts ...grpc.CallOption) (*StringResp, error) {
	out := new(StringResp)
	err := c.cc.Invoke(ctx, "/Location/Print", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationServer is the server API for Location service.
type LocationServer interface {
	Print(context.Context, *LatLng) (*StringResp, error)
}

func RegisterLocationServer(s *grpc.Server, srv LocationServer) {
	s.RegisterService(&_Location_serviceDesc, srv)
}

func _Location_Print_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatLng)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServer).Print(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Location/Print",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServer).Print(ctx, req.(*LatLng))
	}
	return interceptor(ctx, in, info, handler)
}

var _Location_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Location",
	HandlerType: (*LocationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Print",
			Handler:    _Location_Print_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "location.proto",
}
